services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use the dev Dockerfile for development
    volumes:
      - .:/app  # Mount the current directory for live reloading
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True