# Generated by Django 5.1.1 on 2024-11-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='harmonix_api.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='affordability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='professionalism',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='punctuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='qualityOfWork',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
