# Generated by Django 5.1.1 on 2024-11-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0002_remove_rating_review_rating_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='harmonix_api.user'),
            preserve_default=False,
        ),
    ]
