# Generated by Django 5.1.1 on 2024-12-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0007_certificate_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Declined'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountverification',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harmonix_api.certificate'),
        ),
        migrations.AlterField(
            model_name='accountverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harmonix_api.user'),
        ),
        migrations.AddField(
            model_name='accountverification',
            name='attestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harmonix_api.charactereference'),
        ),
    ]
