# Generated by Django 5.1.1 on 2024-12-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0010_rename_charactereference_characterreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountverification',
            name='certificate',
        ),
        migrations.AddField(
            model_name='accountverification',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='AccountVerifications', to='harmonix_api.certificate'),
        ),
    ]
