# Generated by Django 5.1.1 on 2024-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0011_remove_accountverification_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='credential_pics/'),
        ),
    ]
