# Generated by Django 5.1.1 on 2024-12-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonix_api', '0012_alter_accountverification_valid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountverification',
            name='character_references',
        ),
        migrations.AddField(
            model_name='accountverification',
            name='character_references',
            field=models.ManyToManyField(blank=True, related_name='AccountVerifications', to='harmonix_api.characterreference'),
        ),
    ]
